apiVersion: v1
kind: ConfigMap
metadata:
  name: keycloak
data:
  KC_DB: {{ .Values.keycloak.KC_DB | quote}}
  KC_DB_URL: {{ .Values.keycloak.KC_DB_URL | quote}}
  KC_METRICS_ENABLED: {{ .Values.keycloak.KC_METRICS_ENABLED | quote}}
  KC_HOSTNAME_URL: {{ .Values.keycloak.KC_HOSTNAME_URL | quote}}
  KC_HOSTNAME_ADMIN_URL: {{ .Values.keycloak.KC_HOSTNAME_ADMIN_URL | quote}}
  HOSTNAME_BASE: {{ .Values.ingress.HOST | quote}}