version: '3.9'

services:
  student_service:
    container_name: student_service
    build:
      context: user/
      dockerfile: Dockerfile
 
    ports:
      - "8080:5000"
    networks:
      - infrastructure_application
    restart: unless-stopped


networks:
  infrastructure_application:
    external: true

    