version: '3.9'

services:
  student_service:
    container_name: student_service
    build:
      context: user/
      dockerfile: Dockerfile
 
    ports:
      - "5050:5050"
    networks:
      - infrastructure_application
    restart: unless-stopped
  teacher_service:
    container_name: teacher_service
    build:
      context: teacher-panel
      dockerfile: Dockerfile
    volumes:
      - ./teacher-panel/src:/app/src:ro
    ports:
      - 5173:5173
    networks:
      - infrastructure_application
    env_file:
      - ./teacher-panel/.env
  teacher_api:
    container_name: teacher_api
    build:
      context: teacher-api
      dockerfile: Dockerfile
    volumes:
      - ./teacher-api/src:/app/src:ro
    ports:
      - 5000:5000
    networks:
      - infrastructure_application

networks:
  infrastructure_application:
    external: true

    