environment: "prod"

grafana:
  GF_AUTH_GENERIC_OAUTH_API_URL: "https://zeruscloud.com/keycloak/realms/DM885/protocol/openid-connect/userinfo"
  GF_AUTH_GENERIC_OAUTH_AUTH_URL: "https://zeruscloud.com/keycloak/realms/DM885/protocol/openid-connect/auth"
  GF_SERVER_ROOT_URL: "https://zeruscloud.com/grafana/"
  IMAGE: "gcr.io/devsecops-422807/grafana"

