Grafana:
  GF_AUTH_GENERIC_OAUTH_API_URL: "zeruscloud.com/keycloak/realms/DM885/protocol/openid-connect/userinfo"
  GF_AUTH_GENERIC_OAUTH_AUTH_URL: "zeruscloud.com/keycloak/realms/DM885/protocol/openid-connect/auth"
  GF_SERVER_ROOT_URL: "zeruscloud.com/grafana/"