environment: "dev"

secrets:
  GF_AUTH_GENERIC_OAUTH_CLIENT_SECRET: Z3UIkhnpy7fXPKnrhjkrUov1379wUgTU
  POSTGRES_PASSWORD: postgres
  POSTGRES_USER: postgres
  DATA_SOURCE_NAME: postgresql://postgres:postgres@postgres-application:5432/postgres?sslmode=disable

grafana:
  GF_AUTH_GENERIC_OAUTH_API_URL: "https://localhost/keycloak/realms/DM885/protocol/openid-connect/userinfo"
  GF_AUTH_GENERIC_OAUTH_AUTH_URL: "https://localhost/keycloak/realms/DM885/protocol/openid-connect/auth"
  GF_SERVER_ROOT_URL: "https://localhost/grafana/"
  GF_AUTH_GENERIC_OAUTH_TOKEN_URL: "http://keycloak:8080/realms/DM885/protocol/openid-connect/token"
  IMAGE: "grafana-custom"

postgresApplication:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres