apiVersion: v1
kind: Service
metadata:
  name: postgres-keycloak
  labels:
    app: postgres-keycloak
spec:
  ports:
  - port: 5432
  selector:
    app: postgres-keycloak
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-keycloak
spec:
  selector:
    matchLabels:
      app: postgres-keycloak
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: postgres-keycloak
    spec:
      containers:
      - image: postgres:latest
        name: postgres-keycloak
        envFrom:
          - secretRef:
              name: postgres-keycloak
        ports:
        - containerPort: 5432
          name: postgres
        securityContext:
          privileged: false
        volumeMounts:
        - name: postgres-storage
          mountPath: "/var/lib/postgresql/data" 
        resources:
            limits:
              memory: 512Mi
              cpu: "1"
            requests:
              memory: 256Mi
              cpu: "0.2"
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: postgres-keycloak-pvc
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgres-keycloak-pv
  labels:
    app: postgres
spec:
  storageClassName: "standard"
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/data/postgres-keycloak"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-keycloak-pvc
  labels:
    app: postgres
spec:
  storageClassName: "standard"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi