apiVersion: v1
kind: Service
metadata:
  name: postgres-keycloak
spec:
  ports:
  - protocol: TCP
    port: 5432
    targetPort: 5432
  selector:
    app: postgres-keycloak
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-keycloak
spec:
  selector:
    matchLabels:
      app: postgres-keycloak
  template:
    metadata:
      labels:
        app: postgres-keycloak
    spec:
      containers:
      - image: postgres:latest
        name: postgres-keycloak
        envFrom:
          - secretRef:
              name: postgres-keycloak
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: postgres-storage
          mountPath: "/var/lib/postgresql/data" 
      volumes:
      - name: postgres-storage
        persistentVolumeClaim:
          claimName: postgres-keycloak-pvc
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgres-keycloak-pv
spec:
  storageClassName: "standard"
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/mnt/data/postgres-keycloak"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-keycloak-pvc
spec:
  storageClassName: "standard"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi