apiVersion: apps/v1
kind: Deployment
metadata:
  name: adminer
  labels:
    app: adminer
    group: db
spec:
  selector:
    matchLabels:
      app: adminer
  template:
    metadata:
      labels:
        app: adminer
        group: db
    spec:
      containers:
        - name: adminer
          image: adminer:4.7.6-standalone
          env:
            - name: ADMINER_DESIGN
              value: pepa-linha
            - name: ADMINER_DEFAULT_SERVER
              value: postgres-application
---
apiVersion: v1
kind: Service
metadata:
  name: adminer
  labels:
    group: db
spec:
  type: ClusterIP
  selector:
    app: adminer
  ports:
    - port: 8080