apiVersion: v1
kind: Service
metadata:
  name: keycloak
spec:
  selector:
    app: keycloak
  ports:
    - port: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
spec:
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      annotations:
        checksum/config: {{ include "infrastructure/templates/configMaps/keycloak-config.yaml" . | sha256sum }}
        checksum/secret: {{ include "infrastructure/templates/secrets/keycloak-secret.yaml" . | sha256sum }}
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: keycloak/keycloak:24.0.5
          args: ["start-dev", "--import-realm"]
          envFrom:
            - secretRef:
                name: keycloak
            - configMapRef:
                name: keycloak
          volumeMounts:
            - name: keycloak-volume
              mountPath: /opt/keycloak/data/import
      volumes:
        - name: keycloak-volume
          configMap:
            name: keycloak-realm
