apiVersion: v1
kind: Service
metadata:
  name: postgres-keycloak
spec:
  ports:
    - port: 5432
  selector:
    app: postgres-keycloak
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-keycloak
spec:
  selector:
    matchLabels:
      app: postgres-keycloak
  template:
    metadata:
      labels:
        app: postgres-keycloak
    spec:
      containers:
        - image: postgres:latest
          name: postgres-keycloak
          envFrom:
            - secretRef:
                name: postgres-keycloak
          volumeMounts:
            - name: postgres-storage
              mountPath: "/var/lib/postgresql/data"
{{- if eq .Values.environment "prod"}}
              subPath: postgres-key
{{- end }}
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-keycloak-pvc
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: postgres-keycloak-pv
spec:
  storageClassName: "standard"
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
{{- if eq .Values.environment "dev"}}
  hostPath:
    path: "/mnt/data/postgres-keycloak"
{{- else if eq .Values.environment "prod"}}
  gcePersistentDisk:
    pdName: keycloak-disk
    fsType: ext4
{{- end }}
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-keycloak-pvc
spec:
  storageClassName: "standard"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
