apiVersion: v1
data:
  prometheus.yaml: |
    global:
      scrape_interval: 10s

    scrape_configs:
      - job_name: prometheus
        static_configs:
        - targets: ['prometheus:9090']

      - job_name: keycloak
        static_configs:
        - targets: ['keycloak:8080']

      - job_name: promtail
        static_configs:
        - targets: [promtail:9080]

      - job_name: loki
        static_configs:
        - targets: [loki:3100]

      - job_name: node-exporter
        static_configs:
        - targets: [node-exporter:9100]

      - job_name: postgres-exporter
        static_configs:
        - targets: [postgres-exporter:9187]

      - job_name: kube-state-metrics
        static_configs:
        - targets: [kube-state-metrics.kube-system:8080]

      - job_name: kubernetes-nodes-cadvisor
        scrape_interval: 10s
        scrape_timeout: 10s
        scheme: https
        tls_config:
          ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
        bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
        kubernetes_sd_configs:
          - role: node
        relabel_configs:
          - action: labelmap
            regex: __meta_kubernetes_node_label_(.+)
          - target_label: __address__
            replacement: kubernetes.default.svc:443
          - source_labels: [__meta_kubernetes_node_name]
            regex: (.+)
            target_label: __metrics_path__
            replacement: /api/v1/nodes/${1}/proxy/metrics/cadvisor
kind: ConfigMap
metadata:
  name: prometheus