apiVersion: v1
data:
  CUSTOM_KC_APPLICATION_REALM_SECRET: YMnr9LdjNcqjRF94Q0i6PD2Ga2wTccrB
  CUSTOM_KC_GRAFANA_REALM_SECRET: Z3UIkhnpy7fXPKnrhjkrUov1379wUgTU
  KC_DB_PASSWORD: admin
  KC_DB_USERNAME: admin
  KEYCLOAK_ADMIN: admin
  KEYCLOAK_ADMIN_PASSWORD: admin
kind: ConfigMap
metadata:
  labels:
    io.kompose.service: keycloak-keycloak-dev-env
  name: keycloak-dev-env
