apiVersion: v1
data:
  POSTGRES_DB: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_USER: postgres
kind: ConfigMap
metadata:
  labels:
    io.kompose.service: postgres-application-postgres-application-dev-env
  name: postgres-application-dev-env
