
---
# Service for student-service
apiVersion: v1
kind: Service
metadata:
  name: student-service
spec:
  selector:
    app: student-service
  ports:
    - port: 5050

---
# Deployment for student-service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: student-service
  template:
    metadata:
      labels:
        app: student-service
    spec:
      containers:
        - name: student-service
          image: {{ .Values.studentService.IMAGE }}
          imagePullPolicy: {{ .Values.studentService.IMAGE_PULL_POLICY }}
          env:
          - name: SECRET_KEY
            valueFrom:
              configMapKeyRef:
                name: flask-config
                key: SECRET_KEY
          - name: KEYCLOAK_SERVER_URL
            valueFrom:
              configMapKeyRef:
                name: flask-config
                key: KEYCLOAK_SERVER_URL
          - name: KEYCLOAK_REALM
            valueFrom:
              configMapKeyRef:
                name: flask-config
                key: KEYCLOAK_REALM
          - name: KEYCLOAK_CLIENT_ID
            valueFrom:
              configMapKeyRef:
                name: flask-config
                key: KEYCLOAK_CLIENT_ID
          - name: KEYCLOAK_CLIENT_SECRET
            valueFrom:
              configMapKeyRef:
                name: flask-config
                key: KEYCLOAK_CLIENT_SECRET
          - name: KEYCLOAK_REDIRECT_URI
            valueFrom:
              configMapKeyRef:
                name: flask-config
                key: KEYCLOAK_REDIRECT_URI
          - name: KEYCLOAK_ADMIN_USERNAME
            valueFrom:
              configMapKeyRef:
                name: flask-config
                key: KEYCLOAK_ADMIN_USERNAME
          - name: KEYCLOAK_ADMIN_PASSWORD
            valueFrom:
              configMapKeyRef:
                name: flask-config
                key: KEYCLOAK_ADMIN_PASSWORD
          - name: BASE_URL
            valueFrom:
              configMapKeyRef:
                name: flask-config
                key: BASE_URL
          - name: KEYCLOAK_LOGOUT_URL
            valueFrom:
              configMapKeyRef:
                name: flask-config
                key: KEYCLOAK_LOGOUT_URL
          - name: DOCKER_HOST
            value: "tcp://dind:2376"
          - name: DOCKER_CERT_PATH
            value: "/certs/client"
          - name: DOCKER_TLS_VERIFY
            value: "1"
          volumeMounts:
          - name: dind-certs
            mountPath: "/certs/client"
            readOnly: true
      volumes:
      - name: dind-certs
        persistentVolumeClaim:
          claimName: dind-certs

---
# Service for teacher-service
apiVersion: v1
kind: Service
metadata:
  name: teacher-service
spec:
  selector:
    app: teacher-service
  ports:
    - port: 5173

---
# Deployment for teacher-service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: teacher-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: teacher-service
  template:
    metadata:
      labels:
        app: teacher-service
    spec:
      containers:
        - name: teacher-service
          image: {{ .Values.teacherService.IMAGE }}
          imagePullPolicy: {{ .Values.teacherService.IMAGE_PULL_POLICY }}