apiVersion: v1
data:
  prometheus.yaml: |
    global:
      scrape_interval: 10s

    scrape_configs:
      - job_name: prometheus
        static_configs:
        - targets: ['prometheus:9090']

      - job_name: keycloak
        static_configs:
        - targets: ['keycloak:8080']

      - job_name: promtail
        static_configs:
        - targets: [promtail:9080]

      - job_name: loki
        static_configs:
        - targets: [loki:3100]

      - job_name: node-exporter
        static_configs:
        - targets: [node-exporter:9100]

      - job_name: kube-state-metrics
        static_configs:
        - targets: [kube-state-metrics.kube-system.svc.cluster.local:8080]

      - job_name: postgres-exporter
        static_configs:
        - targets: [postgres-exporter:9187]
kind: ConfigMap
metadata:
  name: prometheus