options:
  env:
    - 'CLOUDSDK_COMPUTE_ZONE=europe-west3-a'
    - 'CLOUDSDK_CONTAINER_CLUSTER=dm885-grading-system'

steps: 
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/devsecops-422807/grafana', '-f', 'monitoring/Dockerfile.grafana', './monitoring']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/devsecops-422807/grafana']