options:
  env:
    - 'CLOUDSDK_COMPUTE_ZONE=europe-west3-a'
    - 'CLOUDSDK_CONTAINER_CLUSTER=dm885-grading-system'

steps: 
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/devsecops-422807/python-custom', '-f', 'frontend/user/Dockerfile', 'frontend/user']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/devsecops-422807/python-custom']

- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/devsecops-422807/node-custom', '-f', 'frontend/teacher-panel/Dockerfile', 'frontend/teacher-panel']

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/devsecops-422807/node-custom']