version: '3.9'

services:
  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    ports:
    - 3000:3000
    networks:
      - monitoring
    restart: unless-stopped

  promtail:
    container_name: promtail
    image: grafana/promtail:latest
    expose:
      - 9080
    networks:
      - monitoring
    restart: unless-stopped

  loki:
    container_name: loki
    image: grafana/loki:latest
    expose:
      - 3100
    networks:
      - monitoring
    restart: unless-stopped

  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    volumes:
      - "../monitoring/prometheus.yml:/opt/prometheus/prometheus.yml"
      - prometheus_data:/prometheus
    command: "--config.file=/opt/prometheus/prometheus.yml"
    networks:
      - monitoring
    ports:
      - 9090:9090
    expose:
      - 9090
    restart: unless-stopped

  node-exporter:
    container_name: node-exporter
    image: prom/node-exporter:latest
    restart: unless-stopped
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - "--path.procfs=/host/proc"
      - "--path.rootfs=/rootfs"
      - "--path.sysfs=/host/sys"
      - "--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)"
    expose:
      - 9100
    networks:
      - monitoring

  # cAdvisor service embedded in Kubelet binary
    # Redundant to deploy at the moment

volumes:
  prometheus_data:

networks:
  monitoring:
    external: true
