global:
  scrape_interval: 10s

scrape_configs:
  - job_name: prometheus
    static_configs:
    - targets: ['prometheus:9090']
    metrics_path: /metrics

  - job_name: keycloak
    static_configs:
    - targets: ['keycloak:8080']
    metrics_path: /metrics

  - job_name: promtail
    static_configs:
    - targets: [promtail:9080]
    metrics_path: /metrics

  - job_name: loki
    static_configs:
    - targets: [loki:3100]
    metrics_path: /metrics

  - job_name: node-exporter
    static_configs:
    - targets: [node-exporter:9100]
    metrics_path: /metrics

  - job_name: postgres-exporter
    static_configs:
    - targets: [postgres-exporter:9187]
    metrics_path: /metrics