apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: node-exporter
spec:
  selector:
    matchLabels:
      app: node-exporter
  template:
    metadata:
      labels:
        app: node-exporter
    spec:
      containers:
        - args:
            - --path.procfs=/host/proc
            - --path.sysfs=/host/sys
          name: node-exporter
          image: prom/node-exporter:latest
          volumeMounts:
            - mountPath: /host/proc
              name: proc-volume
              readOnly: true
            - mountPath: /host/sys
              name: sys-volume
              readOnly: true
            - mountPath: /rootfs
              name: rootfs-volume
              readOnly: true
      volumes:
        - name: proc-volume
          hostPath:
            path: /proc
        - name: sys-volume
          hostPath:
            path: /sys
        - name: rootfs-volume
          hostPath:
            path: /
