apiVersion: v1
kind: Secret
metadata:
  name: keycloak
type: Opaque
stringData:
  CUSTOM_KC_APPLICATION_REALM_SECRET: {{ .Values.keycloak.CUSTOM_KC_APPLICATION_REALM_SECRET }}
  CUSTOM_KC_GRAFANA_REALM_SECRET: {{ .Values.keycloak.CUSTOM_KC_GRAFANA_REALM_SECRET }}
  KC_DB_PASSWORD: {{ .Values.keycloak.KC_DB_PASSWORD }}
  KC_DB_USERNAME: {{ .Values.keycloak.KC_DB_USERNAME }}
  KEYCLOAK_ADMIN: {{ .Values.keycloak.KEYCLOAK_ADMIN }}
  KEYCLOAK_ADMIN_PASSWORD: {{ .Values.keycloak.KEYCLOAK_ADMIN_PASSWORD }}
