apiVersion: v1
stringData:
  POSTGRES_USER: {{ .Values.postgresApplication.POSTGRES_USER }}
  POSTGRES_PASSWORD: {{ .Values.postgresApplication.POSTGRES_PASSWORD }}
  DATA_SOURCE_NAME: postgresql://{{ .Values.postgresApplication.POSTGRES_USER }}:{{ .Values.postgresApplication.POSTGRES_PASSWORD }}@postgres-application:5432/postgres?sslmode=disable
kind: Secret
metadata:
  name: postgres-application
type: Opaque