apiVersion: v1
stringData:
  POSTGRES_USER: {{ .Values.keycloak.KC_DB_USERNAME }}
  POSTGRES_PASSWORD: {{ .Values.keycloak.KC_DB_PASSWORD }}
kind: Secret
metadata:
  name: postgres-keycloak
type: Opaque