apiVersion: v1
stringData:
  POSTGRES_USER: {{ .Values.postgresApplication.POSTGRES_USER }}
  POSTGRES_PASSWORD: {{ .Values.postgresApplication.POSTGRES_PASSWORD }}
kind: Secret
metadata:
  name: postgres-application
type: Opaque