# Pulling the official postgres base image
FROM postgres

# Naming default database, user, and password
ENV POSTGRES_DB postgres
ENV POSTGRES_USER postgres
ENV POSTGRES_PASSWORD postgres

# Executing SQL file on startup
COPY infrastructure/relation.sql /docker-entrypoint-initdb.d/