apiVersion: v1
data:
  POSTGRES_PASSWORD: ${{ secrets.KEYCLOAK_POSTGRES_PASSWORD }}
  POSTGRES_USER: ${{ secrets.KEYCLOAK_POSTGRES_USER }}
kind: Secret
metadata:
  name: postgres-keycloak
type: Opaque