apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      annotations:
        checksum/config: {{ include "monitoring/templates/configMaps/grafana-datasources-config.yaml" . | sha256sum }}
        checksum/config: {{ include "monitoring/templates/configMaps/grafana.yaml" . | sha256sum }}
      labels:
        app: grafana
    spec:
      containers:
        - name: grafana
          image: "{{ .Values.grafana.image }}:{{ .Values.grafana.tag }}"
{{- if eq .Values.environment "dev"}}
          imagePullPolicy: Never
{{- end }}
          envFrom:
            - configMapRef:
                name: grafana
            - secretRef:
                name: grafana
            - configMapRef:
                name: postgres-application
            - secretRef:
                name: postgres-application
          volumeMounts:
            - name: grafana-datasources-config
              mountPath: /etc/grafana/provisioning/datasources/
      volumes:
        - name: grafana-datasources-config
          configMap:
            name: grafana-datasources-config
---
apiVersion: v1
kind: Service
metadata:
  name: grafana
spec:
  selector:
    app: grafana
  ports:
    - port: 3000
