apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: keycloak/keycloak:latest
          args:
            - "-Dkeycloak.migration.action=import"
            - "-Dkeycloak.migration.provider=singleFile"
            - "-Dkeycloak.migration.file=/opt/keycloak/data/import/realm-export.json"
            - "-Dkeycloak.migration.strategy=OVERWRITE_EXISTING"
          env:
            - name: PROXY_ADDRESS_FORWARDING
              value: "true"
            - name: KEYCLOAK_FRONTEND_URL
              value: "https://zeruscloud.com/keycloak"
          envFrom:
            - secretRef:
                name: keycloak
            - configMapRef:
                name: keycloak
          volumeMounts:
            - name: keycloak-volume
              mountPath: /opt/keycloak/data/import
      volumes:
        - name: keycloak-volume
          configMap:
            name: keycloak-realm
