# Use an official Python runtime as a parent image
FROM python:3.12

# Set the working directory in the container
WORKDIR /usr/src/app

# Copy the current directory contents into the container at /usr/src/app
COPY . .

# Install any needed packages specified in requirements.txt, or list them explicitly
RUN pip install -r requirements.txt 

# Define environment variable
ENV FLASK_APP=app.py
ENV FLASK_RUN_HOST=localhost

# Run app.py when the container launches
CMD ["flask", "run"]
